### ISSUE TITLE
cannot fill in password

### ISSUE THREAD

**Issue by Uitzondering** [0xbitcoin/0xbitcoin-miner#4]
when creating account in the win app i just cannot add any password, the cursos doesnt move. using Win10. 
all other commands work.

![image](https://user-images.githubusercontent.com/36543712/36317654-f516b392-133d-11e8-9a75-7e5a0e614899.png)

**Comment by 0xbitcoin** [comment]
Hello, the cursor will indeed not move as it is in a 'hiding' mode for added security incase somebody is looking over your shoulder.  Just type and know that it is registering inputs.
