### ISSUE TITLE
Is there currently a way to import private key for an account?

### ISSUE THREAD

**Issue by daevski** [0xbitcoin/0xbitcoin-miner#5]
I ended up in a state with the miner (on windows) where my account and web3 provider were both "undefined" - so I deleted the vaultdata and created a new account. Since there was eth in the older account, I'm wondering if it can be imported into the miner again, so that I can continue mining into that account.

**Comment by 0xbitcoin** [comment]
Unfortunately there is not for security reasons.  It is generally a faux pas to be copy and pasting ethereum private keys around willy nilly.  The recommendation is that you type 'account list' to see your private key.  Then you can copy this to clipboard with 'ctrl+shift+c'.  (thats just a fun fact.)   Then you can paste the private key into say, Parity or Metamask and spend eth and tokens from it.

**Comment by daevski** [comment]
Fair enough, thank you for the response! (Congrats on level 16 difficulty today, btw! It would appear that it is being mined!)
